/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadora;

import javax.swing.JOptionPane;

/**
 *
 * @author joao Bardock
 */
public class interface_ extends javax.swing.JFrame {

    /**
     * Creates new form interface_
     */
    public interface_() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Lnum = new javax.swing.JTextField();
        ldeno = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ldivisor = new javax.swing.JButton();
        resdiv = new javax.swing.JLabel();
        resres = new javax.swing.JLabel();
        lsomador = new javax.swing.JButton();
        lmult = new javax.swing.JButton();
        lsubtra = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("2º Numero");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("1º Numero");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Resultado");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Resto");

        ldivisor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ldivisor.setText("Dividir/");
        ldivisor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ldivisorActionPerformed(evt);
            }
        });

        resdiv.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        resdiv.setText("0");

        resres.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        resres.setText("0");

        lsomador.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lsomador.setText("+");
        lsomador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lsomadorActionPerformed(evt);
            }
        });

        lmult.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lmult.setText("Mult *");
        lmult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lmultActionPerformed(evt);
            }
        });

        lsubtra.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lsubtra.setText("-");
        lsubtra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lsubtraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(Lnum, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(ldeno, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(lmult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ldivisor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel3)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lsomador, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lsubtra, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(134, 134, 134)
                            .addComponent(resres))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(51, 51, 51)
                            .addComponent(resdiv))))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ldeno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lsomador)
                    .addComponent(ldivisor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lmult)
                    .addComponent(lsubtra))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(resdiv))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(resres))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ldivisorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ldivisorActionPerformed
 
   if (!Lnum.getText().equals("") && !ldeno.getText().equals("")){
     
      float n = Float.parseFloat(Lnum.getText());// esse parse float converte string para float;
      float d = Float.parseFloat(ldeno.getText());
      float div= n/d;
      float res= n%d;
      
      resdiv.setText(Float.toString(div));// a variavel botao rediv recebe o valor da divisao e converte
      //com o tostring de float para string
      
      resres.setText(Float.toString(res));
      
}
   else
            JOptionPane.showMessageDialog(null,"Favor inserir os valores para fazer a operação");

        
    }//GEN-LAST:event_ldivisorActionPerformed

    private void lsomadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lsomadorActionPerformed

        
       if(!Lnum.getText().equals("") && !ldeno.getText().equals("")) {
        int n = Integer.parseInt(Lnum.getText());// esse parse int converte string para int;
        int d = Integer.parseInt(ldeno.getText());
        float soma= n+d;
        float res= 0;
        resdiv.setText(Float.toString(soma));// a variavel de texto recebe o parametro calculado em soma
        resres.setText(Float.toString(res));// a variavel de texto recebe o parametro calculado em res;
      
       }
       else
           JOptionPane.showMessageDialog(null,"Favor inserir os valores para fazer a operação");
        

// TODO add your handling code here:
    }//GEN-LAST:event_lsomadorActionPerformed

    private void lmultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lmultActionPerformed
     
        
        
        if(!Lnum.getText().equals("") && !ldeno.getText().equals(""))
        {
       int n = Integer.parseInt(Lnum.getText());
        int d = Integer.parseInt(ldeno.getText());
        float mult= n*d;
        float res= 0;
        
         resdiv.setText(Float.toString(mult));// a variavel de texto recebe o parametro calculado em soma
        resres.setText(Float.toString(res));
        }
        else{
        
        JOptionPane.showMessageDialog(null,"Favor inserir os valores para fazer a operação");
        }
           
    }//GEN-LAST:event_lmultActionPerformed

    private void lsubtraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lsubtraActionPerformed
      
         if(!Lnum.getText().equals("") && !ldeno.getText().equals(""))
        {
        int n = Integer.parseInt(Lnum.getText());
        int d = Integer.parseInt(ldeno.getText());
        float sub= n-d;
        float res= 0;
        
        resdiv.setText(Float.toString(sub));// a variavel de texto recebe o parametro calculado em soma
        resres.setText(Float.toString(res));
        
        }
         else
         {
         JOptionPane.showMessageDialog(null,"Favor inserir os valores para fazer a operação");
         
         }
         
        
        
    }//GEN-LAST:event_lsubtraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interface_.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interface_.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interface_.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interface_.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interface_().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Lnum;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField ldeno;
    private javax.swing.JButton ldivisor;
    private javax.swing.JButton lmult;
    private javax.swing.JButton lsomador;
    private javax.swing.JButton lsubtra;
    private javax.swing.JLabel resdiv;
    private javax.swing.JLabel resres;
    // End of variables declaration//GEN-END:variables
}
